import { describe, expect, it } from "vitest";
import { openAPIDocToTypes } from "./openapi-to-types.js";
import type { OpenAPIDocument } from "../openapi/types.js";

const HEADER = "// This file is auto-generated by @bas-in/basin-js. Do not edit.";

function makeDoc(overrides: Partial<OpenAPIDocument> = {}): OpenAPIDocument {
  return {
    openapi: "3.0.3",
    info: { title: "Basin REST API", version: "0.1.0" },
    paths: {},
    ...overrides,
  };
}

describe("openAPIDocToTypes — auto-generated comment", () => {
  it("output starts with the auto-generated comment", () => {
    const out = openAPIDocToTypes(makeDoc());
    expect(out.startsWith(HEADER)).toBe(true);
  });

  it("output exports a Database interface", () => {
    const out = openAPIDocToTypes(makeDoc());
    expect(out).toContain("export interface Database");
  });
});

describe("openAPIDocToTypes — basic table from paths", () => {
  const doc: OpenAPIDocument = makeDoc({
    paths: {
      "/rest/v1/users": {
        get: {
          operationId: "getUsers",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id", "email"],
                      properties: {
                        id: { type: "integer" },
                        email: { type: "string" },
                        created_at: { type: "string", format: "date-time" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  });

  it("emits a users table block", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("users:");
  });

  it("Row has id as number", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("id: number;");
  });

  it("Row has email as string", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("email: string;");
  });

  it("date-time format fields typed as string", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("created_at: string;");
  });

  it("Row, Insert, Update blocks are all present", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("Row:");
    expect(out).toContain("Insert:");
    expect(out).toContain("Update:");
  });
});

describe("openAPIDocToTypes — nullable field", () => {
  const doc: OpenAPIDocument = makeDoc({
    paths: {
      "/rest/v1/profiles": {
        get: {
          operationId: "getProfiles",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id"],
                      properties: {
                        id: { type: "integer" },
                        email: { type: "string", nullable: true },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  });

  it("nullable field is typed as T | null in Row", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("email: string | null;");
  });

  it("nullable field is optional in Insert", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("email?: string | null;");
  });
});

describe("openAPIDocToTypes — field with default → optional in Insert", () => {
  const doc: OpenAPIDocument = makeDoc({
    paths: {
      "/rest/v1/items": {
        get: {
          operationId: "getItems",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id", "name"],
                      properties: {
                        id: { type: "integer", default: 0 },
                        name: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  });

  it("field with default is required in Row", () => {
    const out = openAPIDocToTypes(doc);
    const rowSection = out.slice(
      out.indexOf("Row:"),
      out.indexOf("Insert:"),
    );
    expect(rowSection).toContain("id: number;");
  });

  it("field with default is optional in Insert", () => {
    const out = openAPIDocToTypes(doc);
    const insertSection = out.slice(
      out.indexOf("Insert:"),
      out.indexOf("Update:"),
    );
    expect(insertSection).toContain("id?: number;");
  });

  it("all fields are optional in Update", () => {
    const out = openAPIDocToTypes(doc);
    const updateSection = out.slice(out.indexOf("Update:"));
    expect(updateSection).toContain("id?: number;");
    expect(updateSection).toContain("name?: string;");
  });
});

describe("openAPIDocToTypes — multiple tables", () => {
  const doc: OpenAPIDocument = makeDoc({
    paths: {
      "/rest/v1/users": {
        get: {
          operationId: "getUsers",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id"],
                      properties: { id: { type: "integer" } },
                    },
                  },
                },
              },
            },
          },
        },
      },
      "/rest/v1/products": {
        get: {
          operationId: "getProducts",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["sku"],
                      properties: { sku: { type: "string" } },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  });

  it("emits both tables", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("users:");
    expect(out).toContain("products:");
  });
});

describe("openAPIDocToTypes — non-table paths ignored", () => {
  const doc: OpenAPIDocument = makeDoc({
    paths: {
      "/rest/v1/users": {
        get: {
          operationId: "getUsers",
          responses: {
            "200": {
              description: "OK",
              content: {
                "application/json": {
                  schema: {
                    type: "array",
                    items: {
                      type: "object",
                      required: ["id"],
                      properties: { id: { type: "integer" } },
                    },
                  },
                },
              },
            },
          },
        },
      },
      "/rest/v1/users/rpc/my_func": {
        get: {
          operationId: "myFunc",
          responses: { "200": { description: "OK" } },
        },
      },
    },
  });

  it("nested paths (not matching /rest/v1/<table>) are ignored", () => {
    const out = openAPIDocToTypes(doc);
    expect(out).toContain("users:");
    expect(out).not.toContain("my_func:");
  });
});
