import type { OpenAPIDocument, OpenAPISchema } from "../openapi/types.js";

function mapPrimitiveType(schema: OpenAPISchema): string {
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "string") return "string";
  if (schema.type === "array") {
    const itemType = schema.items ? mapType(schema.items) : "unknown";
    return `${itemType}[]`;
  }
  if (schema.type === "object") {
    if (!schema.properties) return "Record<string, unknown>";
    const fields = Object.entries(schema.properties)
      .map(([k, v]) => `${k}: ${mapType(v)}`)
      .join("; ");
    return `{ ${fields} }`;
  }
  return "unknown";
}

function mapType(schema: OpenAPISchema): string {
  const base = mapPrimitiveType(schema);
  return schema.nullable === true ? `${base} | null` : base;
}

interface TableField {
  name: string;
  tsType: string;
  required: boolean;
  hasDefault: boolean;
  nullable: boolean;
}

function extractRowFields(schema: OpenAPISchema): TableField[] {
  if (!schema.properties) return [];
  const requiredSet = new Set(schema.required ?? []);
  return Object.entries(schema.properties).map(([name, prop]) => ({
    name,
    tsType: mapType(prop),
    required: requiredSet.has(name),
    hasDefault: "default" in prop,
    nullable: prop.nullable === true,
  }));
}

function renderRowType(fields: TableField[]): string {
  const lines = fields.map((f) => `      ${f.name}: ${f.tsType};`);
  return `{\n${lines.join("\n")}\n    }`;
}

function renderInsertType(fields: TableField[]): string {
  const lines = fields.map((f) => {
    const optional = f.hasDefault || f.nullable || !f.required ? "?" : "";
    return `      ${f.name}${optional}: ${f.tsType};`;
  });
  return `{\n${lines.join("\n")}\n    }`;
}

function renderUpdateType(fields: TableField[]): string {
  const lines = fields.map((f) => `      ${f.name}?: ${f.tsType};`);
  return `{\n${lines.join("\n")}\n    }`;
}

interface TableEntry {
  name: string;
  fields: TableField[];
}

function findTablesFromPaths(doc: OpenAPIDocument): TableEntry[] {
  const tables: TableEntry[] = [];
  const seen = new Set<string>();

  for (const [path, pathItem] of Object.entries(doc.paths)) {
    const match = /^\/rest\/v1\/([^/]+)$/.exec(path);
    if (!match) continue;
    const tableName = match[1];
    if (!tableName || seen.has(tableName)) continue;
    seen.add(tableName);

    const getOp = pathItem.get;
    if (!getOp) {
      tables.push({ name: tableName, fields: [] });
      continue;
    }

    const resp200 = getOp.responses["200"];
    const schema =
      resp200?.content?.["application/json"]?.schema?.items ??
      resp200?.content?.["application/json"]?.schema;

    if (!schema) {
      tables.push({ name: tableName, fields: [] });
      continue;
    }

    tables.push({ name: tableName, fields: extractRowFields(schema) });
  }

  if (tables.length === 0 && doc.components?.schemas) {
    for (const [name, schema] of Object.entries(doc.components.schemas)) {
      if (seen.has(name)) continue;
      seen.add(name);
      tables.push({ name, fields: extractRowFields(schema) });
    }
  }

  return tables;
}

export function openAPIDocToTypes(doc: OpenAPIDocument): string {
  const tables = findTablesFromPaths(doc);

  const tableBlocks = tables
    .map((t) => {
      const row = renderRowType(t.fields);
      const insert = renderInsertType(t.fields);
      const update = renderUpdateType(t.fields);
      return (
        `      ${t.name}: {\n` +
        `        Row: ${row};\n` +
        `        Insert: ${insert};\n` +
        `        Update: ${update};\n` +
        `      }`
      );
    })
    .join("\n");

  return (
    `// This file is auto-generated by @bas-in/basin-js. Do not edit.\n` +
    `export interface Database {\n` +
    `  public: {\n` +
    `    tables: {\n` +
    `${tableBlocks}\n` +
    `    }\n` +
    `  }\n` +
    `}\n`
  );
}
